"""
Django settings for portfolio_project project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
import urllib.parse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env(path: Path) -> None:
    """Загрузка .env; override=True — ключи из файла перекрывают пустые переменные ОС."""
    if not path.exists():
        return
    try:
        from dotenv import load_dotenv

        load_dotenv(path, override=True)
        return
    except ImportError:
        pass
    try:
        text = path.read_text(encoding='utf-8')
    except OSError:
        return
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if '=' not in line:
            continue
        key, _, val = line.partition('=')
        key = key.strip()
        val = val.strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in '\'\"':
            val = val[1:-1]
        if key:
            os.environ[key] = val


_load_env(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hmflnh2e3-00fx2+v8k@_gs2p_kfegr4a4qwi7znqa6ul1q)2^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_project.wsgi.application'

# Database — на Vercel SQLite недоступен для записи; нужен PostgreSQL (DATABASE_URL).
def _database_from_url(url: str) -> dict:
    if url.startswith("postgres://"):
        url = "postgresql://" + url[len("postgres://") :]
    parsed = urllib.parse.urlparse(url)
    name = urllib.parse.unquote(parsed.path.lstrip("/"))
    cfg = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": name,
        "USER": urllib.parse.unquote(parsed.username or ""),
        "PASSWORD": urllib.parse.unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or 5432),
        "OPTIONS": {},
    }
    query = urllib.parse.parse_qs(parsed.query)
    if query.get("sslmode"):
        cfg["OPTIONS"]["sslmode"] = query["sslmode"][0]
    return cfg


def _resolve_database_url() -> str | None:
    """Совместимость с Neon/Vercel и ручными именами переменных."""
    for key in (
        "DATABASE_URL",
        "POSTGRES_URL",
        "POSTGRES_PRISMA_URL",
    ):
        v = (os.environ.get(key) or "").strip()
        if v:
            return v
    return None


_db_url = _resolve_database_url()


def _is_vercel_function_runtime() -> bool:
    """Только рантайм Serverless-функции (файлы под /var/task). На билде Vercel использует /vercel/path0 и
    часто выставляет VERCEL=1 — нельзя требовать DATABASE_URL на этапе сборки."""
    return str(BASE_DIR).startswith("/var/task")


if _db_url:
    DATABASES = {"default": _database_from_url(_db_url)}
elif _is_vercel_function_runtime():
    raise ImproperlyConfigured(
        "На Vercel нужен PostgreSQL: задайте DATABASE_URL в Settings → Environment Variables "
        "(для Production и Preview). Подключите БД (Neon / Vercel Postgres), вставьте строку подключения, "
        "затем выполните python manage.py migrate против этой БД."
    )
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Кастомная панель /dashboard/ (django.contrib.auth)
LOGIN_URL = '/dashboard/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/dashboard/login/'

# LLM: Groq (free API key) or Gemini (см. console.groq.com, aistudio.google.com)
LLM_PROVIDER = os.environ.get('LLM_PROVIDER', 'groq')
GROQ_API_KEY = (os.environ.get('GROQ_API_KEY') or '').strip()
GROQ_MODEL = (os.environ.get('GROQ_MODEL') or 'llama-3.3-70b-versatile').strip()
GEMINI_API_KEY = (os.environ.get('GEMINI_API_KEY') or '').strip()
GEMINI_MODEL = (os.environ.get('GEMINI_MODEL') or 'gemini-2.5-flash').strip()
# Повторы при HTTP 429 от Gemini (слишком много запросов / квота)
GEMINI_HTTP_RETRIES = int(os.environ.get('GEMINI_HTTP_RETRIES') or '4')
GITHUB_TOKEN = (os.environ.get('GITHUB_TOKEN') or '').strip()

# PageSpeed Insights API (те же данные, что pagespeed.web.dev) — Google Cloud Console
GOOGLE_PAGESPEED_API_KEY = (os.environ.get('GOOGLE_PAGESPEED_API_KEY') or '').strip()

# HTML-панель управления (/panel/): пароль из .env. В production обязателен.
PORTFOLIO_PANEL_SECRET = os.environ.get('PORTFOLIO_PANEL_SECRET', '').strip()
