# Generated by Django 4.2.16 on 2026-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_markdown', models.TextField(blank=True, help_text='Генерируется из видимых проектов через кнопку в разделе проектов.', verbose_name='Резюме (Markdown)')),
                ('cv_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='CV обновлено')),
            ],
            options={
                'verbose_name': 'Резюме и настройки портфолио',
                'verbose_name_plural': 'Резюме и настройки портфолио',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название (в админке)')),
                ('slug', models.SlugField(blank=True, help_text='Пусто — создаётся из названия.', max_length=220, unique=True)),
                ('author_notes', models.TextField(blank=True, help_text='Что важно рассказать посетителю — учитывается при генерации.', verbose_name='Ваше описание проекта')),
                ('git_repository_url', models.URLField(blank=True, help_text='Публичный GitHub/GitLab. По нему подтягивается контекст для LLM.', max_length=600, verbose_name='URL Git-репозитория')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать на главной странице')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Меньшее значение — выше в списке.', verbose_name='Порядок сортировки')),
                ('display_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок на сайте')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='Категория')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание (карточка)')),
                ('stat1_value', models.CharField(blank=True, max_length=40, verbose_name='Показатель 1 — значение')),
                ('stat1_label', models.CharField(blank=True, max_length=80, verbose_name='Показатель 1 — подпись')),
                ('stat2_value', models.CharField(blank=True, max_length=40, verbose_name='Показатель 2 — значение')),
                ('stat2_label', models.CharField(blank=True, max_length=80, verbose_name='Показатель 2 — подпись')),
                ('tech_tags', models.JSONField(blank=True, default=list, help_text='JSON-массив строк, например: ["Django", "PostgreSQL"]', verbose_name='Стек (теги)')),
                ('demo_url', models.URLField(blank=True, max_length=600, verbose_name='Ссылка «Посмотреть проект»')),
                ('icon_emoji', models.CharField(blank=True, default='🚀', max_length=12, verbose_name='Иконка (эмодзи)')),
                ('llm_last_error', models.TextField(blank=True, editable=False, verbose_name='Последняя ошибка LLM')),
                ('enriched_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Обогащено LLM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
