# Generated by Django 4.2.16 on 2026-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='llm_frozen_fields',
            field=models.JSONField(blank=True, default=list, help_text='Список имён полей: LLM при обогащении не меняет их.', verbose_name='Поля карточки без перезаписи LLM'),
        ),
    ]
