# Generated by Django 6.0.4 on 2026-05-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_llm_frozen_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='card_image',
            field=models.ImageField(blank=True, help_text='Показывается сверху карточки вместо эмодзи. Рекомендуем 1200×600 или широкий кроп.', null=True, upload_to='projects/cards/', verbose_name='Скриншот / изображение карточки'),
        ),
        migrations.AddField(
            model_name='project',
            name='card_image_url',
            field=models.URLField(blank=True, help_text='Если файл не загружен: прямая ссылка на изображение (например с вашего CDN).', max_length=800, verbose_name='Или URL картинки'),
        ),
    ]
