# Generated by Django 6.0.4 on 2026-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_seed_bereke_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('category', models.CharField(choices=[('fullstack', 'Full Stack'), ('ai', 'AI'), ('qa', 'QA'), ('python', 'Python'), ('frontend', 'Front-end')], db_index=True, max_length=16, verbose_name='Категория')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тег стека',
                'verbose_name_plural': 'Теги стека',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
    ]
