# Generated by Django 4.2.16 on 2026-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mcp_server_tech_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Заголовок')),
                ('body', models.TextField(help_text='2–4 предложения. Можно с абзацами.', verbose_name='Описание')),
                ('icon', models.CharField(blank=True, help_text='Необязательно: один символ или эмодзи.', max_length=16, verbose_name='Иконка (эмодзи)')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Меньше — выше в списке.', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Преимущество для клиента',
                'verbose_name_plural': 'Преимущества для клиента',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
