# Generated by Django 4.2.16 on 2026-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_seed_client_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployment_platforms',
            field=models.JSONField(blank=True, default=list, help_text='Хостинг, CI/CD, облако (список строк). Показываются на карточке рядом с качеством.', verbose_name='Платформы'),
        ),
        migrations.AddField(
            model_name='project',
            name='pagespeed_cwv_note',
            field=models.CharField(blank=True, help_text='Одна строка для карточки; если пусто — берётся текст из ответа API.', max_length=500, verbose_name='Формулировка про Core Web Vitals'),
        ),
        migrations.AddField(
            model_name='project',
            name='pagespeed_diag_bad',
            field=models.TextField(blank=True, help_text='2–4 фразы; если пусто — автоматический выбор из Lighthouse.', verbose_name='Узкие места'),
        ),
        migrations.AddField(
            model_name='project',
            name='pagespeed_diag_good',
            field=models.TextField(blank=True, help_text='2–4 короткие фразы; если пусто — подсказки из ответа API.', verbose_name='Что уже хорошо'),
        ),
        migrations.AddField(
            model_name='project',
            name='pagespeed_profile_note',
            field=models.CharField(blank=True, help_text='Честное сравнение: например лендинг vs тяжёлый SPA — разные профили метрик.', max_length=400, verbose_name='Контекст типа проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='pagespeed_public_report_url',
            field=models.URLField(blank=True, help_text='Скопируйте URL из адресной строки после анализа на pagespeed.web.dev (необязательно).', max_length=2000, verbose_name='Прямая ссылка на отчёт PageSpeed'),
        ),
        migrations.AddField(
            model_name='project',
            name='pagespeed_report',
            field=models.JSONField(blank=True, default=dict, help_text='Мобильная и десктопная оценка Lighthouse через API (как на pagespeed.web.dev).', verbose_name='PageSpeed Insights'),
        ),
    ]
